version: '3.7'

services:

  api:
    container_name: dev-community-api-container
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "8000:3000"
    volumes:
      - ./src:/app/src
    depends_on:
      - api-db
    networks:
      - mongo-network


  api-db:
    container_name: dev-community-api-db
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=
      - MONGO_INITDB_ROOT_PASSWORD=
      - MONGO_INITDB_DATABASE=
    ports:
      - "27017:27017"
    networks:
      - mongo-network


networks:
    mongo-network:
        driver: bridge
